=== EPiCS/soundgates/software/Soundgates/model/atomicComponent.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="AtomicSoundComponent">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Type" type="xs:string"/>
      <xs:element name="Ports">
        <xs:complexType>
          <xs:sequence>
              <xs:element name="Port">
                <xs:attribute name="Name" type="xs:string"/>
                <xs:attribute name="Direction" type="xs:string"/>
                <xs:attribute name="DataType" type="xs:string"/>
              </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Code">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Simulation" type="xs:string"/>
            <xs:element name="Hardware" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== EPiCS/soundgates/software/AtomicComponents/SineGenerator.xml
<?xml version="1.0"?>

<AtomicSoundComponent xmlns="soundgates" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../Soundgates model/atomicComponent.xsd">
	<Type>Sine generator</Type>
	<Ports>
		<Port Name="Frequency" Direction="IN" DataType="INT"/>
		<Port Name="Output" Direction="OUT" DataType="SOUND"/>
	</Ports>
	<Code>
		<Simulation>
			PD Code
		</Simulation>
		<Hardware>
			VHDL Stuff
		</Hardware>
	</Code>
</AtomicSoundComponent>
