=== EPiCS/soundgates/software/editor/Soundgates/model/atomicComponent.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="AtomicSoundComponent">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Type" type="xs:string"/>
      <xs:element name="Ports">
        <xs:complexType>
          <xs:sequence>
              <xs:element name="Port">
                <xs:attribute name="Name" type="xs:string"/>
                <xs:attribute name="Direction" type="xs:string"/>
                <xs:attribute name="DataType" type="xs:string"/>
              </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
	  <xs:element name="Properties">
		<xs:sequence>
			<xs:choice>
				<xs:element name="IntProperty">
					<xs:attribute name="Name" type="xs:string"/>
					<xs:attribute name="InitialValue" type="xs:integer" use="optional" />
				</xs:element>
				<xs:element name="FloatProperty">
					<xs:attribute name="Name" type="xs:string"/>
					<xs:attribute name="InitialValue" type="xs:decimal" use="optional" />
				</xs:element>
				<xs:element name="BoolProperty">
					<xs:attribute name="Name" type="xs:string"/>
					<xs:attribute name="InitialValue" type="xs:boolean" use="optional" />
				</xs:element>
			</xs:choice>
		</xs:sequence>
	  </xs:element>
      <xs:element name="Code">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Simulation" type="xs:string"/>
            <xs:element name="Hardware" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== EPiCS/soundgates/software/editor/AtomicComponents/NumericMultiplication/NumericMultiplication.xml
<?xml version="1.0"?>

<AtomicSoundComponent xmlns="soundgates" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../Soundgates model/atomicComponent.xsd">
	<Type>NumericMultiplication</Type>
	<Ports>
		<Port Name="Multiplicand" Direction="IN" DataType="CONTROL"/>
		<Port Name="Multiplier" Direction="IN" DataType="CONTROL"/>
		<Port Name="Product" Direction="OUT" DataType="CONTROL"/>
	</Ports>
	<Properties>
	</Properties>
	<Code>
		<Simulation/>
		<Hardware>
			VHDL Stuff
		</Hardware>
	</Code>
</AtomicSoundComponent>

=== EPiCS/soundgates/software/editor/AtomicComponents/NumericAddition/NumericAddition.xml
<?xml version="1.0"?>

<AtomicSoundComponent xmlns="soundgates" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../Soundgates model/atomicComponent.xsd">
	<Type>NumericAddition</Type>
	<Ports>
		<Port Name="Summand1" Direction="IN" DataType="FLOAT"/>
		<Port Name="Summand2" Direction="IN" DataType="FLOAT"/>
		<Port Name="Result" Direction="OUT" DataType="FLOAT"/>
	</Ports>
	<Properties>
	</Properties>
	<Code>
		<Simulation>
		</Simulation>
		<Hardware>
			VHDL Stuff
		</Hardware>
	</Code>
</AtomicSoundComponent>

=== EPiCS/soundgates/software/AtomicComponents/Dummy.xml
<?xml version="1.0"?>

<AtomicSoundComponent xmlns="soundgates" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../Soundgates model/atomicComponent.xsd">
	<Type>Dummy</Type>
	<Ports>
		<Port Name="Sound_In" Direction="IN" DataType="SOUND"/>
		<Port Name="Sound_Out" Direction="OUT" DataType="SOUND"/>
	</Ports>
	<Properties>
		<FloatProperty Name="FloatProp"/>
		<IntProperty Name="IntProp1" InitialValue="30"/>
		<IntProperty Name="IntProp2"/>
		<BoolProperty Name="BoolProp" InitialValue="True"/>
	</Properties>
	<Code>
		<Simulation>
			PD Code
		</Simulation>
		<Hardware>
			VHDL Stuff
		</Hardware>
	</Code>
</AtomicSoundComponent>

=== EPiCS/soundgates/software/editor/AtomicComponents/NumericSineGenerator/NumericSineGenerator.xml
<?xml version="1.0"?>

<AtomicSoundComponent xmlns="soundgates" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../Soundgates model/atomicComponent.xsd">
	<Type>NumericSineGenerator</Type>
	<Ports>
		<Port Name="Resolution" Direction="IN" DataType="CONTROL"/>
		<Port Name="Frequency" Direction="IN" DataType="CONTROL"/>
		<Port Name="Output" Direction="OUT" DataType="CONTROL"/>
	</Ports>
	<Properties>
	</Properties>
	<Code>
		<Simulation>
		</Simulation>
		<Hardware>
			VHDL Stuff
		</Hardware>
	</Code>
</AtomicSoundComponent>

=== EPiCS/soundgates/software/AtomicComponents/Constant.xml
<?xml version="1.0"?>

<AtomicSoundComponent xmlns="soundgates" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../Soundgates model/atomicComponent.xsd">
	<Type>Constant</Type>
	<Ports>
		<Port Name="Value" Direction="OUT" DataType="FLOAT"/>
	</Ports>
	<Properties>
		<FloatProperty Name="Value" InitialValue="0"/>
	</Properties>
	<Code>
		<Simulation>
			PD Code
		</Simulation>
		<Hardware>
			VHDL Stuff
		</Hardware>
	</Code>
</AtomicSoundComponent>

=== EPiCS/soundgates/software/editor/AtomicComponents/NumericDivision/NumericDivision.xml
<?xml version="1.0"?>

<AtomicSoundComponent xmlns="soundgates" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../Soundgates model/atomicComponent.xsd">
	<Type>NumericDivision</Type>
	<Ports>
		<Port Name="Dividend" Direction="IN" DataType="CONTROL"/>
		<Port Name="Divisor" Direction="IN" DataType="CONTROL"/>
		<Port Name="Quotient" Direction="OUT" DataType="CONTROL"/>
	</Ports>
	<Properties>
	</Properties>
	<Code>
		<Simulation/>
		<Hardware>
			VHDL Stuff
		</Hardware>
	</Code>
</AtomicSoundComponent>

=== EPiCS/soundgates/software/editor/AtomicComponents/Multiplication/Multiplication.xml
<?xml version="1.0"?>

<AtomicSoundComponent xmlns="soundgates" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../Soundgates model/atomicComponent.xsd">
	<Type>Multiplication</Type>
	<Ports>
		<Port Name="SoundIn" Direction="IN" DataType="SOUND"/>
		<Port Name="Multiplier" Direction="IN" DataType="FLOAT"/>
		<Port Name="SoundOut" Direction="OUT" DataType="SOUND"/>
	</Ports>
	<Properties>
	</Properties>
	<Code>
		<Simulation>
		</Simulation>
		<Hardware>
			VHDL Stuff
		</Hardware>
	</Code>
</AtomicSoundComponent>

=== EPiCS/soundgates/software/editor/AtomicComponents/NumericSubtraction/NumericSubtraction.xml
<?xml version="1.0"?>

<AtomicSoundComponent xmlns="soundgates" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../Soundgates model/atomicComponent.xsd">
	<Type>NumericSubtraction</Type>
	<Ports>
		<Port Name="Minuend " Direction="IN" DataType="FLOAT"/>
		<Port Name="Subtrahend" Direction="IN" DataType="FLOAT"/>
		<Port Name="Difference" Direction="OUT" DataType="FLOAT"/>
	</Ports>
	<Properties>
	</Properties>
	<Code>
		<Simulation>
		</Simulation>
		<Hardware>
			VHDL Stuff
		</Hardware>
	</Code>
</AtomicSoundComponent>
